In [1]:
# NewYork Citibike Program 2020 -  Oct - Dec trip data
import pandas as pd
import datetime
import numpy as np
import os

In [2]:
# Get NewYork Citibike tripdata csv files from Oct - Dec 2020
filepath_oct = os.path.join("Citi Bike Data" ,"JC-202010-citibike-tripdata.csv")
filepath_nov = os.path.join("Citi Bike Data" ,"JC-202011-citibike-tripdata.csv")
filepath_dec = os.path.join("Citi Bike Data" ,"JC-202012-citibike-tripdata.csv")

nycbike_2020oct = pd.read_csv(filepath_oct)
nycbike_2020nov = pd.read_csv(filepath_nov)
nycbike_2020dec = pd.read_csv(filepath_dec)

In [3]:
nycbike_2020oct.head(5)

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,156,2020-10-01 00:02:40.2600,2020-10-01 00:05:17.0140,3186,Grove St PATH,40.719586,-74.043117,3270,Jersey & 6th St,40.725289,-74.045572,42293,Subscriber,1996,1
1,143,2020-10-01 00:02:53.5020,2020-10-01 00:05:16.9650,3186,Grove St PATH,40.719586,-74.043117,3270,Jersey & 6th St,40.725289,-74.045572,44740,Subscriber,1998,1
2,305,2020-10-01 00:04:31.3160,2020-10-01 00:09:36.3840,3273,Manila & 1st,40.721651,-74.042884,3269,Brunswick & 6th,40.726012,-74.050389,41369,Subscriber,1988,2
3,1097,2020-10-01 00:05:18.3680,2020-10-01 00:23:36.1240,3199,Newport Pkwy,40.728745,-74.032108,3281,Leonard Gordon Park,40.745910,-74.057271,42285,Customer,2001,1
4,277,2020-10-01 00:09:17.5990,2020-10-01 00:13:55.5150,3199,Newport Pkwy,40.728745,-74.032108,3638,Washington St,40.724294,-74.035483,45231,Subscriber,1965,1

In [4]:
nycbike_last_quater_2020 = pd.concat([nycbike_2020oct,nycbike_2020nov,nycbike_2020dec])

In [5]:
# Output from Oct - Dec 2020 citibike tripdata to CSV file 
filepath_2020_last_quater = os.path.join("Citi Bike Data" ,"JC-2020_last_quater-citibike-tripdata.csv")
nycbike_last_quater_2020.to_csv(filepath_2020_last_quater, index=False)
nycbike_last_quater_2020.tail(5)

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
11689,1750,2020-12-31 23:07:44.0030,2020-12-31 23:36:54.4710,3199,Newport Pkwy,40.728745,-74.032108,3199,Newport Pkwy,40.728745,-74.032108,40440,Customer,1969,0
11690,1519,2020-12-31 23:18:00.2630,2020-12-31 23:43:19.8590,3184,Paulus Hook,40.714145,-74.033552,3195,Sip Ave,40.730897,-74.063913,46340,Customer,1969,0
11691,1761,2020-12-31 23:31:09.4620,2021-01-01 00:00:31.3290,3195,Sip Ave,40.730897,-74.063913,3270,Jersey & 6th St,40.725289,-74.045572,40907,Customer,1998,1
11692,637,2020-12-31 23:35:45.4640,2020-12-31 23:46:22.7300,3681,Grand St,40.715178,-74.037683,3199,Newport Pkwy,40.728745,-74.032108,42250,Customer,1969,0
11693,1607,2020-12-31 23:48:34.5750,2021-01-01 00:15:22.3090,3267,Morris Canal,40.712419,-74.038526,3267,Morris Canal,40.712419,-74.038526,48742,Subscriber,1982,1